### ISSUE TITLE
Y a pas

### ISSUE THREAD

**Issue by teidova21** [AntoninHuaut/EtuEDT-Deno#2]
Y a pas l'edt depuis 3j, il met not found sur les requêtes [ici](https://edtapi.maner.fr/v2/1/1185) et [ici](https://edtapi.maner.fr/v2/1).

url : [https://edt.maner.fr/](https://edt.maner.fr/)

**Comment by AntoninHuaut** [comment]
Merci du report, le problème est fixé !
